version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - guac

  guacd:
    image: glyptodon/guacd
    restart: always
    networks:
      - guac

  guac:
    image: glyptodon/guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - guac
    depends_on:
      - postgres
      - guacd
    
volumes:
  data:
    driver: local

networks:
  guac:
    driver: bridge
